api_platform:
  defaults:
    pagination_items_per_page: 10
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  collection:
      pagination:
        # The default name of the parameter handling the page number.
        page_parameter_name: 'page'

        # The name of the query parameter to enable or disable pagination.
        enabled_parameter_name: 'pagination'

        # The name of the query parameter to set the number of items per page.
        items_per_page_parameter_name: 'itemsPerPage'

        # The name of the query parameter to enable or disable the partial pagination.
        partial_parameter_name: 'partial'

